.PHONY: generate generate-go generate-ts gofmt-gen clean install-tools

# Proto source directory
PROTO_DIR := proto
# Generated output directory
GEN_DIR := gen

# The single buf resolution shared with the verification gate (scripts/buf.sh:
# fail-closed to the lockfile-pinned install, no PATH fallback, no run-time
# download). generate-ts used to call `npx @bufbuild/buf generate`, which
# downloads and runs registry-latest whenever the package is not installed
# locally — so a tree could be generated by one buf and linted by another, and
# `make generate` inside the gate's generated-drift step would report drift or
# clean depending on which version npx happened to fetch.
#
# Resolved from the Makefile's own directory (not CURDIR) so `make -C` and
# `make -f` still find it.
MAKEFILE_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
BUF := $(MAKEFILE_DIR)scripts/buf.sh

# The code-generating plugins are pinned to the module versions go.mod
# already records, discovered at run time rather than written down twice:
# @latest let a protoc-gen-go release change the version stamp inside every
# .pb.go file and fail the generated-drift gate on unrelated PRs. Bumping the
# module in go.mod moves the plugin with it. `go list -m` fails loudly if a
# module disappears, so an empty version can never silently mean @latest.
# protoc-go-inject-tag is a build-only tool absent from go.mod and stays
# @latest deliberately.
install-tools:
	go install google.golang.org/protobuf/cmd/protoc-gen-go@$$(go list -m -f '{{.Version}}' google.golang.org/protobuf)
	go install connectrpc.com/connect/cmd/protoc-gen-connect-go@$$(go list -m -f '{{.Version}}' connectrpc.com/connect)
	go install github.com/favadi/protoc-go-inject-tag@latest

# NOT prerequisites: make may satisfy those in any order, and concurrently
# under -j. This pipeline is strictly ordered — protoc writes the files,
# inject-tags rewrites their struct tags, gofmt cleans up after inject-tags —
# so the stages are invoked in sequence instead.
generate:
	$(MAKE) generate-go
	$(MAKE) inject-tags
	$(MAKE) gofmt-gen
	$(MAKE) generate-ts

# protoc-go-inject-tag rewrites struct tags but does NOT re-run gofmt
# afterwards, so its output can leave the generated .pb.go files with
# multi-field struct alignment that gofmt -l flags. Run gofmt -w over
# the gen directory once at the end of the Go pipeline to keep the
# committed gen files clean against `gofmt -l ./...`.
gofmt-gen:
	gofmt -w $(GEN_DIR)/go

# protoc writes outputs; it never deletes outputs whose INPUT is gone. Removing
# or MOVING a .proto therefore leaves an orphaned .pb.go behind — and because a
# .pb.go registers its descriptors at init, the deleted service stays live at
# runtime and in protoregistry while every drift check (`git diff` on gen/)
# reports clean. Renaming the proto package is the worst case: both namespaces
# register, and whichever init runs first wins.
#
# So the generated directories are emptied before regeneration. Scoped to the
# powermanage/v1 output dirs rather than $(GEN_DIR) so nothing else under gen/
# is at risk. When the output path itself moves, these patterns MUST move with
# it and the abandoned directory has to go — a stale path here silently stops
# cleaning anything.
generate-go:
	@rm -f $(GEN_DIR)/go/powermanage/v1/*.pb.go $(GEN_DIR)/go/powermanage/v1/powermanagev1connect/*.connect.go
	@mkdir -p $(GEN_DIR)/go/powermanage/v1
	protoc \
		--proto_path=$(PROTO_DIR) \
		--go_out=$(GEN_DIR)/go \
		--go_opt=paths=source_relative \
		--connect-go_out=$(GEN_DIR)/go \
		--connect-go_opt=paths=source_relative \
		$(PROTO_DIR)/powermanage/v1/*.proto

inject-tags:
	protoc-go-inject-tag -input="$(GEN_DIR)/go/powermanage/v1/*.pb.go"

# Same orphan problem as generate-go: buf writes outputs and leaves behind any
# whose .proto input was deleted, and gen/ts is archived directly into the npm
# release, so a stale *_pb.ts ships to consumers as a live export.
generate-ts:
	@rm -f $(GEN_DIR)/ts/powermanage/v1/*_pb.ts
	$(BUF) generate

clean:
	rm -rf $(GEN_DIR)
